---
title: "UniversalBank-MLProject"
author: "Yeshil Bangera"
date: "06/10/2022"
output: github_document
---


## Loading all required Packages

```{r}
library(caret)
library(lattice)
library(ggplot2)
library(FNN)
```
## Loading th dataset, eliminating and changing columns as factors 

```{r}
loan_df <- read.csv("UniversalBank.csv")
loan_df <- subset(loan_df, select = -5)
loan_df <- subset(loan_df, select = -1)
#loan.df$Education <-as.factor(loan.df$Education)
#loan.df$Securities.Account<-as.factor(loan.df$Securities.Account)
#loan.df$CD.Account <-as.factor(loan.df$CD.Account)
#loan.df$Online <-as.factor(loan.df$Online)
#loan.df$CreditCard <-as.factor(loan.df$CreditCard)
#loan.df$Personal.Loan<-as.factor(loan.df$Personal.Loan)
head(loan_df)
View(loan_df)
```

## Slpiting the data into training and validation. Also creating a data frame containing the new data.
```{r}
set.seed(111)
train.index <- sample(row.names(loan_df), 0.75*dim(loan_df)[1])
valid.index <- setdiff(row.names(loan_df), train.index)
train.df <- loan_df[train.index, ]
valid.df <- loan_df[valid.index, ]
## new customer
#Age = 40, Experience = 10, Income = 84, Family = 2, CCAvg = 2, Education_1 = 0, Education_2 = 1,
#Education_3 = 0, Mortgage = 0, Securities Account = 0, CD Account = 0, Online = 1, and Credit Card = 1.
new.df <- data.frame(Age = 40, Experience = 10, Income = 84, Family = 2, CCAvg = 2, Education=2, Mortgage = 0, Securities.Account = 0, CD.Account = 0, Online = 1, CreditCard = 1)
new.df
```


```{r}
# Initialize normalization of training , validation data
train.norm.df <- train.df
valid.norm.df <- valid.df
loan.norm.df <- loan_df
new.norm.df <- new.df
head(loan.norm.df)

```


```{r}
str(loan.norm.df)
```


```{r}
#using preProcess from the caret library to normalize the dataset
norm.values <- preProcess(train.df[,c(1,2,3,4,5,7)], method = c("center", "scale"))
train.norm.df[, c(1,2,3,4,5,7)] <- predict(norm.values, train.df[,c(1,2,3,4,5,7)])
valid.norm.df[, c(1,2,3,4,5,7)] <- predict(norm.values, valid.df[, c(1,2,3,4,5,7)]) 
loan.norm.df[, c(1,2,3,4,5,7)] <- predict(norm.values, loan_df[,c(1,2,3,4,5,7)]) 
new.norm.df[,c(1,2,3,4,5,7)] <- predict(norm.values, new.df[,c(1,2,3,4,5,7)])
```


```{r}
#install.packages('e1071', dependencies=TRUE)
# initialize a data frame with two columns: k, and accuracy.
accuracy.df <- data.frame(k = seq(1,20,1), accuracy = rep(0,20))
# compute knn for different k on validation.
for(i in 1:20) 
  { knn.pred <- knn(train.norm.df[, -8], valid.norm.df[, -8], 
                    cl = train.norm.df[,8], k = i)
  
accuracy.df[i,2] <- confusionMatrix(as.factor(knn.pred), as.factor(valid.norm.df[,8]))$overall[1]
}
print(accuracy.df)
```


```{r}
#Find the best k
best.k <- accuracy.df$k[which.max(accuracy.df$accuracy)] 
best.k
```


```{r}
# use knn() to compute knn.
#Knn documentation:https://www.rdocumentation.org/packages/class/versions/7.3-17/topics/knn
# knn() is available in library FNN (provides a list of the nearest neighbors)
# and library class (allows a numerical output variable).
library(FNN)
#unlist(train.norm.df)
#as.numeric(new.norm.df)
#nn2 <- knn(train = train.norm.df[, -8], test = new.norm.df,
# cl = train.norm.df[, 8], k = 3)
nn2 <- knn(train = train.norm.df[, -8], test = new.norm.df, 
           cl = train.norm.df[,8], k = best.k) 
nn2
```


```{r}
#Classification of loans in validation data
knn.pred.new <- knn(train.norm.df[, -8], test = valid.norm.df[,-8],
                    cl = train.norm.df[,8], k = best.k)
#Confustion matrix of validation
cf.val <- confusionMatrix(as.factor(knn.pred.new),as.factor(valid.norm.df[,8]))
cf.val
```

```{r}
# ## Explanation:
# The data is been trained using 75% of the data set and the rest 25% is used as validation. K-NN algorithm is used to predict if the loan is accepted or not (0 OR 1). Later preprocess function is used to normalize the data. The "center" argument in the preprocess function subtracts the mean of the predictor's data from the predictor values while "scale" divides by the standard deviation.A for loop is used for implementing different values of k to identify the k with best accuracy. Then the best k value which is 3 in this case is used with the new data and a confusion matrix is created.

```


##Conclusion:
A) Level: nn2 returned value 0 which means loan not accepted
B) Best value of K is 3
C) Confusion matrix of validation has an Accuracy : 0.9656 i.e. 96.56%








